#!/usr/bin/env bash

# Original by SolDoesTech https://github.com/SolDoesTech/HyprV2

# Calculate updates for each service
AUR=$(yay -Qua | wc -l)
OFFICIAL=$(checkupdates | wc -l)

# Case/switch for each service updates
case $1 in
    aur) echo " $AUR";;
    official) echo " $OFFICIAL";;
esac

# If the parameter is "update", update all services
if [ "$1" = "update" ]; then
    alacritty -e sh -c 'yay -Syu'
fi

# If there aren't any parameters, return the total number of updates
if [ "$1" = "" ]; then
    # Calculate total number of updates
    COUNT=$((OFFICIAL+AUR))
    # If there are updates, the script will output the following:   Updates
    # If there are no updates, the script will output nothing.

    if [[ "$COUNT" != "0" ]]
    then
        # This Update symbol is RTL. So &#x202d; is left-to-right override.
        echo "$COUNT"
    fi
    exit 0
fi
